# Model projections and scenario analysis
\chaptermark{Projections}
<!-- Not in UCL -->
<!-- How is it used? By who? Not only policies (IPCC) but several applications.  -->

## Climate scenarios
### Representative Concentration Pathway (RCP scenarios)
- How scenarios are defined
- How current emissions are measured and attributed to different factors? 

### Different models, different RCP 
- The central role of ESM: coupling to Atmosphere and Ocean and feedbacks
- Here refers to preivous Chapter 10
- list some examples and differences: IPSL, HadGEM, etc...
- <!-- - ENSEMBLE simulations, importance of experiments for historical and future simulation assessement (FLUXNET, paleo-climat, FACE, remote-sensing, etc…) -->

### Use of RCP in vegetation modelling
- ENSEMBLE simulations
- IPCC
- Example of applications

### How can we evaluate future scenarios? 
- FACE
- Rainfall exclusion experiments
- Natural gradient (Iceland and soil temperature based on volcano and geothermy)

### The central role of Paleo-climatology and historical datasets. 
- Good performance for past and current conditions is mandatory to evaluate future scenarios

## Land-use scenarios
### Construction of Land-use scenarios
- Hyde for historical land-use, https://themasites.pbl.nl/tridion/en/themasites/hyde/
- Scenario for future land-use

--> We can follow the same structure as for RCP? 

### How can we evaluate land use scenarios? 
- Based on historical data
- Remote sensing 

## Management scenarios
### Construction of Land-use scenarios

### How can we evaluate management scenarios? 
- 

## Some concrete applications of vegetation models
- As a conclusion of the whole course I see a nice diagram that we constructed throughout the course with small boxes added to each others and we link that to all the possible application 
