# (PART) Practicals {-}

# Contributing to this document {-}

## First steps {-}
First, visit the course webpage on https://github.com/femeunier/VegMod_course, and fork it to your own github account. Open a RStudio session and (if it is your first time with git) introduce yourself:

```{bash, eval = FALSE}
git config --global user.name "FULLNAME"
git config --global user.email you@yourdomain.example.com
```

Note that you can do every single step below using the terminal and the git tabs in RStudio. Clone the newly forked folder to your local machine: 

```{bash, eval = FALSE}
git clone https://github.com/femeunier/VegMod_course.git
```

or using SSH (to set up it first, see for instance https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh)

```{bash, eval = FALSE}
git clone git@github.com:femeunier/VegMod_course.git
```

Define upstream

```{bash, eval = FALSE}
cd VegMod_course
git remote add upstream git@github.com:femeunier/VegMod_course.git
```

## New pull request {-}

Get the latest code from the main repository

```{bash, eval = FALSE}
git pull upstream master
```

Create a new branch (here new_branch is the new branch's name)

```{bash, eval = FALSE}
git checkout -b new_branch
```

Do some coding, add files and commit them

```{bash, eval = FALSE}
git add filepath
git commit -m “Message”
```

Push your changes to your github

```{bash, eval = FALSE}
git push origin new_branch
```

Open the PR online by visiting your github repository. To ease those previous steps you can take advantage of the git GUI in RStudio. To do so, create a new project from an existing director

# Supporting  material {-}
Crash course, basic programming (R), theory about model evaluation etc.

# Practical A {-}
PC-room, supervised exercise

Simple model on diurnal variation in solar angle, radiation extinction and photosynthesis in vegetation types with different and canopy structure and LAI: grassland, broadleaved forest, coniferous forest

Scale: aggregated stand level (big leaf model)

Methodological focus: model formulation: translating a few equations into code

Methodological focus: compiling code, running model, reading input-output

# Practical B {-}

Group work, report, PC room

Modelling diurnal cycle of carbon and water fluxes for flux tower sites (Savanna’s Sahel)

Scale: aggregated stand level

Methodological focus: model-data comparison (goodness-of-fit), simple parameter optimisation

# Practical C {-}

PC-room, supervised exercise

Modelling the size structure of a temperate forest (stand diameter distribution)

Scale: forest stand

Methodological focus: initial conditions

# Practical D {-}

Group work, report, PC room

Modelling carbon stocks (above and belowground) and fluxes

Scale: ecosystem

Methodological focus: Spinup and sensitivity analysis (testing which climate variables have strongest impact on stocks)

# Practical E {-}

PC-room, supervised exercise

Simulating forest succession, meta-analysis of trait dataset to prescribe vegetation functional composition (using PEcAn-framework)

Scale: landscape

Methodological focus: parameter meta-analysis (PFT construction), data assimilation
 
# Practical F {-}

PC-room, group work, microteaching

Climate/land use/management scenario analysis

Scale: site/globe? (Pecan framework) each group choses a question and a model

Methodological focus: sensitivity and uncertainty analysis
